## train & test script
# scale 2
##################################################################################################################################
#CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX2 --scale 2 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 128 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --chop --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6

CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX2_test --scale 2 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 128 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --chop --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6 --pre_train ../experiment/MXBASRN_BIX2.pt --test_only --data_test Set5+Set14+B100+Urban100+Manga109 #--save_results

# scale 3
##################################################################################################################################
#CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX3 --scale 3 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 192 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6

CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX3_test --scale 3 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 192 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6 --pre_train ../experiment/MXBASRN_BIX3.pt --test_only --data_test Set5+Set14+B100+Urban100+Manga109 #--save_results

# scale 4
##################################################################################################################################
#CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX4 --scale 4 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 256 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6

CUDA_VISIBLE_DEVICES=0 python main.py --model MXBASRN --save MXBASRN_BIX4_test --scale 4 --n_resgroups 6 --n_resblocks 8 --n_feats 128 --ext sep --print_model --patch_size 256 --batch_size 16 --no_attention --n_threads 8 --shift_mean True --use_multi_axis_atten --multi_axis_atten_method pure --atten_noself --no_perfect_balanced_blocking --res_scale 1 --small_upsampling_head --small_upsampling_head_with_width_threshold --small_upsampling_head_with_width_threshold_value 64 --n_GPUs 1 --dir_data /data/SR --with_layer_norm_channel --configurable_attention --configurable_attention_num 6 --pre_train ../experiment/MXBASRN_BIX4.pt --test_only --data_test Set5+Set14+B100+Urban100+Manga109 #--save_results

